# Auto-generated structure.spec

dir: ./
dir: ./attn/
dir: ./bin/
dir: ./config/
dir: ./lib/
dir: ./modules/
dir: ./modules/prototype/
dir: ./modules/unit_testing/
dir: ./modules/unit_testing/environment/
dir: ./modules/unit_testing/experimentation/
dir: ./modules/unit_testing/fsm/
dir: ./root-test/
dir: ./system/
dir: ./system-test/
dir: ./system-test/features/
dir: ./system-test/garbage_detector/
dir: ./system-test/garbage_detector/tmp/
dir: ./system-test/helpers/
dir: ./system-test/structure_generator/
dir: ./system-test/structure_ignore/
dir: ./system-test/structure_negative_tests/
dir: ./system-test/structure_negative_tests/tmp/
dir: ./system-test/structure_validator/
dir: ./system-test/structure_validator/tmp/
dir: ./system/exit-codes/
dir: ./system/make/
dir: ./test/
dir: ./tools/
dir: ./tools/git-hooks/
dir: ./tools/providers/
dir: ./tools/providers/localfs/
dir: ./tools/providers/terraform/
dir: ./tools/release/
dir: ./tools/structure/
file: ./.github/pull_request_template.md
file: ./.gitignore
file: ./.structure.ignore
file: ./CHANGELOG.md
file: ./Focus.txt
file: ./Makefile
file: ./README.generated.md
file: ./README.md
file: ./attn/context-status.rf.sh
file: ./attn/context-status.sh
file: ./config/enforcer_tests.txt
file: ./config/policy.rules.yml
file: ./config/runtime.cfg
file: ./config/runtime_flags.sh
file: ./lib/logger.sh
file: ./lib/logger_wrapper.sh
file: ./lib/source_OR_fail.sh
file: ./main.sh
file: ./modules/prototype/envManager.sh
file: ./modules/prototype/fsm_git_handler.sh
file: ./modules/prototype/prototypeManager.env
file: ./modules/prototype/prototype_manager2.sh
file: ./modules/prototype/prototype_requirements_02-09-25.txt
file: ./modules/prototype/truths_fsm_handler.json
file: ./modules/unit_testing/environment/context_testing.bats
file: ./modules/unit_testing/fsm/fsm_execute_git_command_tests.sh
file: ./modules/unit_testing/fsm/fsm_input_tests.bats
file: ./modules/unit_testing/fsm/fsm_input_tests.sh
file: ./modules/unit_testing/fsm/transition_testing.bats.sh
file: ./modules/unit_testing/handler.sh
file: ./modules/unit_testing/module.state
file: ./smoke.sh
file: ./system-test/enforce_policy.bats
file: ./system-test/features/drift_monitoring.feature
file: ./system-test/garbage_detector/test-ignore-valid.bats
file: ./system-test/garbage_detector/test-untracked-garbage.bats
file: ./system-test/main-context-check-mock.bats
file: ./system-test/main-preflight.bats
file: ./system-test/main-structure-validator-mock.bats
file: ./system-test/structure_generator/test-generate-spec.bats
file: ./system-test/structure_ignore/.structure.ignore
file: ./system-test/structure_ignore/test-validate-ignore.bats
file: ./system-test/structure_negative_tests/test-broken-symlink.bats
file: ./system-test/structure_negative_tests/test-invalid-structure.bats
file: ./system-test/structure_validator/test-raw-path.bats
file: ./system-test/structure_validator/test-valid-structure.bats
file: ./system-test/structure_validator_queries.bats
file: ./system-test/test-main.bats
file: ./system-test/testing-setup.sh
file: ./system/comparator.txt
file: ./system/exit-codes/exit_codes_validator.sh
file: ./system/make/garbage.mk
file: ./system/make/health.mk
file: ./system/make/help.mk
file: ./system/make/hooks.mk
file: ./system/make/modules.mk
file: ./system/make/preflight.mk
file: ./system/make/preflight_shared.mk
file: ./system/make/structure.mk
file: ./system/make/test.mk
file: ./system/structure_spec_validator.sh
file: ./system/structure_validator.rf.sh
file: ./system/structure_validator.sh
file: ./system/test_logger.bats
file: ./system/test_logger_min.sh
file: ./system/validate_structure.sh
file: ./test/test_source_safe.bats
file: ./test/toggle_module_contracts.bats
file: ./toggle.sh
file: ./tools/README.generated.md
file: ./tools/aggregate_structure.sh
file: ./tools/bats-guard.sh
file: ./tools/check_git_trash.sh
file: ./tools/detect_garbage.sh
file: ./tools/doctor.sh
file: ./tools/enforce_policy.sh
file: ./tools/exit_codes_enforcer.sh
file: ./tools/fix_missing_specs.sh
file: ./tools/gen_readme.rf.rf.sh
file: ./tools/gen_readme.rf.sh
file: ./tools/gen_readme.sh
file: ./tools/gen_readme_updates.sh
file: ./tools/generate_all_module_specs.sh
file: ./tools/git-hooks/pre-commit
file: ./tools/git-hooks/pre-merge-check.sh
file: ./tools/git-hooks/pre-push
file: ./tools/install-hooks.sh
file: ./tools/pre-git-switch.sh
file: ./tools/release/gen_notes.sh
file: ./tools/scan_duplicate_targets.sh
file: ./tools/setup.sh
file: ./tools/structure/structure_snapshot_gen.sh
file: ./tools/structure_compare.sh
file: ./tools/test_coverage_summary_real.bats
file: ./tools/test_pre_git_switch.bats
file: ./tools/utili-sourcing.sh
file: ./tools/validate_ignore.sh
