# Auto-generated structure.spec

dir: ./
dir: ./attn/
dir: ./bin/
dir: ./ci/
dir: ./ci/dora/
dir: ./ci/git/
dir: ./ci/jq/
dir: ./ci/roi/
dir: ./ci/voi/
dir: ./config/
dir: ./docs/
dir: ./lib/
dir: ./lib/policy/
dir: ./lib/queries/
dir: ./lib/testdata/
dir: ./system/
dir: ./system/exit-codes/
dir: ./system/make/
dir: ./templates/
dir: ./test/
dir: ./test/acceptance/
dir: ./test/bin-tests/
dir: ./test/e2e/
dir: ./test/e2e/features/
dir: ./test/e2e/garbage_detector/
dir: ./test/e2e/helpers/
dir: ./test/e2e/structure_generator/
dir: ./test/e2e/structure_ignore/
dir: ./test/e2e/structure_negative_tests/
dir: ./test/e2e/structure_validator/
dir: ./test/integration/
dir: ./test/lib-tests/
dir: ./test/unit/
dir: ./tools/
dir: ./tools/git-hooks/
dir: ./tools/providers/
dir: ./tools/providers/localfs/
dir: ./tools/providers/terraform/
dir: ./tools/release/
dir: ./tools/structure/
dir: ./util/
file: ./.github/CODEOWNERS
file: ./.github/pull_request_template.md
file: ./.github/workflows/acceptance.yml
file: ./.github/workflows/check-purity.yml
file: ./.github/workflows/churn-pr.yml
file: ./.github/workflows/ci-hours.yml
file: ./.github/workflows/deploy.yml
file: ./.github/workflows/dora-basics.yml
file: ./.github/workflows/dora-health.yml
file: ./.github/workflows/first-pass.yml
file: ./.github/workflows/leadtime-dryrun.yml
file: ./.github/workflows/maat-coupling.yml
file: ./.github/workflows/metrics-preflight.yml
file: ./.github/workflows/nightly-metrics.yml
file: ./.github/workflows/pr-tests.yml
file: ./.github/workflows/pr-up-to-date.yml
file: ./.github/workflows/risk-update.yml
file: ./.github/workflows/roi-aggregator.yml
file: ./.github/workflows/roi-baseline.yml
file: ./.github/workflows/scope-check.yml
file: ./.github/workflows/scope.yml
file: ./.github/workflows/shellcheck.yml
file: ./.github/workflows/structural_drift.yml
file: ./.github/workflows/validate-hooks.yml
file: ./.gitignore
file: ./.structure.ignore
file: ./Makefile
file: ./README.generated.md
file: ./attn/context-status.rf.sh
file: ./attn/context-status.sh
file: ./bin/deploy.sh
file: ./bin/deploy_exec.sh
file: ./bin/emit-env
file: ./bin/gen-scope.sh
file: ./bin/main.sh
file: ./bin/risk_pull.sh
file: ./ci/build.sh
file: ./ci/check-env-shape.sh
file: ./ci/check_contracts.sh
file: ./ci/check_frames.sh
file: ./ci/check_layering.sh
file: ./ci/check_predicates.sh
file: ./ci/check_queries.sh
file: ./ci/checklib.sh
file: ./ci/dora/collect-events.sh
file: ./ci/dora/compute-dora.py
file: ./ci/dora/event-append.sh
file: ./ci/dora/health.sh
file: ./ci/dora/lt_from_sha.sh
file: ./ci/dora/test-lead.py
file: ./ci/env-shape.baseline
file: ./ci/failure_taxonomy.yml
file: ./ci/git/lib-risk.sh
file: ./ci/git/prepare-ref.sh
file: ./ci/jq/dora_lt_validate.jq
file: ./ci/jq/events_summary.jq
file: ./ci/jq/events_validate.jq
file: ./ci/lib.sh
file: ./ci/probe.sh
file: ./ci/repro.sh
file: ./ci/roi/build_inputs.sh
file: ./ci/roi/compute_roit.py
file: ./ci/roi/emit_ci_hours.py
file: ./ci/roi/extract_run_stats.sh
file: ./ci/roi/fetch_artifacts.sh
file: ./ci/roi/first-pass.sh
file: ./ci/roi/gen_ci_hours.sh
file: ./ci/roi/parsers.py
file: ./ci/roi/run_stats.jq
file: ./ci/roi/shadow_diff.py
file: ./ci/run.sh
file: ./ci/setup.sh
file: ./ci/test.sh
file: ./ci/test_github_timings.py
file: ./ci/test_toggl_parser.py
file: ./ci/triage.sh
file: ./ci/voi/void_from_dora.py
file: ./config/policy.rules.yml
file: ./config/runtime.cfg
file: ./config/runtime_flags.sh
file: ./config/scope.overrides.yaml
file: ./config/scope.yaml
file: ./darwin_memory.sh
file: ./docs/CHANGELOG.md
file: ./docs/README.generated.md
file: ./docs/README.md
file: ./lib/README.md
file: ./lib/cmd.sh
file: ./lib/cmd2.sh
file: ./lib/command_contracts.sh
file: ./lib/contract_dsl.sh
file: ./lib/contract_env.sh
file: ./lib/contract_fs.sh
file: ./lib/contracts.sh
file: ./lib/contracts2.sh
file: ./lib/contracts_dsl.sh
file: ./lib/contracts_env.sh
file: ./lib/darwin_memory.sh
file: ./lib/enums.sh
file: ./lib/env_init.sh
file: ./lib/environment.contract.sh
file: ./lib/evaluate.contract.sh
file: ./lib/evaluate.frame.sh
file: ./lib/evaluate.sh
file: ./lib/file.sh
file: ./lib/findings.json
file: ./lib/frame.rf.sh
file: ./lib/frame.sh
file: ./lib/load-frame.sh
file: ./lib/main.sh
file: ./lib/memory.sh
file: ./lib/parse.sh
file: ./lib/pipe.sh
file: ./lib/policy/enforce_policy_p3.sh
file: ./lib/policy/enforce_record
file: ./lib/policy/enforce_record_tests.bats
file: ./lib/policy/isolated_policy_tests.bats
file: ./lib/policy/negative-e2e.bats
file: ./lib/policy/out.tsv
file: ./lib/policy/p1-p3smoke.sh
file: ./lib/policy/p1p3aggregate.bats
file: ./lib/policy/p1p3smoke.bats
file: ./lib/policy/p2_predicates.bats
file: ./lib/policy/p2p3smoke.bats
file: ./lib/policy/policy_query_p1.sh
file: ./lib/policy/policy_query_tests.bats
file: ./lib/policy/predicates-shim.sh
file: ./lib/policy/run_bats.sh
file: ./lib/policy/runner.sh
file: ./lib/policy/smk23.sh
file: ./lib/policy/smk_1-2.bats
file: ./lib/policy/smk_1-2.sh
file: ./lib/policy/smoke_test_policy.query.sh
file: ./lib/policy/testE2e.bats
file: ./lib/policy/test_shim.bats
file: ./lib/policy/transform_policy_p2.sh
file: ./lib/policy/transform_policy_rules.sh
file: ./lib/policy/transform_policy_rules_shim
file: ./lib/policy/verify_pipeline.sh
file: ./lib/predicates.sh
file: ./lib/primitive_checks.bats
file: ./lib/purity.sh
file: ./lib/queries.sh
file: ./lib/queries/darwin_memory.sh
file: ./lib/queries/queries.rules.sh
file: ./lib/queries/rules.sh
file: ./lib/queries/session.queries.sh
file: ./lib/queries/sha256.sh
file: ./lib/rules.json
file: ./lib/run-table.sh
file: ./lib/run_with_frame.sh
file: ./lib/testdata/prefer_stdin.tsv
file: ./lib/testdata/should_read_stdin.tsv
file: ./lib/trace.sh
file: ./lib/tty.sh
file: ./lib/vmmapframe.sh
file: ./lib/with_contract_env.sh
file: ./lib/with_contracts.sh
file: ./scope.yaml
file: ./system/exit-codes/exit_codes_validator.sh
file: ./system/make/garbage.mk
file: ./system/make/guard_rails.mk
file: ./system/make/guard_rails.sh
file: ./system/make/health.mk
file: ./system/make/help.mk
file: ./system/make/hooks.mk
file: ./system/make/modules.mk
file: ./system/make/preflight.mk
file: ./system/make/preflight_shared.mk
file: ./system/make/structure.mk
file: ./system/make/test.mk
file: ./system/smoke-structure-validator.sh
file: ./system/structure
file: ./system/structure_spec_validator.sh
file: ./system/structure_validator.rf.sh
file: ./system/structure_validator.sh
file: ./system/validate_structure.sh
file: ./test/acceptance/acceptance.bats
file: ./test/acceptance/assert_upper.sh
file: ./test/acceptance/domain.log.jsonl
file: ./test/acceptance/domain_probe.sh
file: ./test/acceptance/env_from_probe.sh
file: ./test/acceptance/run_acceptance.sh
file: ./test/bin-tests/main-context-check-mock.bats
file: ./test/bin-tests/main-preflight.bats
file: ./test/bin-tests/main-structure-validator-mock.bats
file: ./test/bin-tests/smoke_test.sh
file: ./test/bin-tests/test-core__derive_root.bats
file: ./test/bin-tests/test-main.bats
file: ./test/e2e/enforce_policy.bats
file: ./test/e2e/features/drift_monitoring.feature
file: ./test/e2e/garbage_detector/test-ignore-valid.bats
file: ./test/e2e/garbage_detector/test-untracked-garbage.bats
file: ./test/e2e/helpers/.gitkeep
file: ./test/e2e/structure_generator/test-generate-spec.bats
file: ./test/e2e/structure_ignore/.structure.ignore
file: ./test/e2e/structure_ignore/test-validate-ignore.bats
file: ./test/e2e/structure_negative_tests/test-broken-symlink.bats
file: ./test/e2e/structure_negative_tests/test-invalid-structure.bats
file: ./test/e2e/structure_validator/test-raw-path.bats
file: ./test/e2e/structure_validator/test-valid-structure.bats
file: ./test/e2e/structure_validator_queries.bats
file: ./test/e2e/testing-setup.sh
file: ./test/integration/hooks_install.bats
file: ./test/integration/runner_hooks_test.sh
file: ./test/integration/test_pre_git_switch.bats
file: ./test/lib-tests/test_logger.bats
file: ./test/lib-tests/test_logger_min.sh
file: ./test/lib-tests/test_source_safe.bats
file: ./test/toggle_module_contracts.sh
file: ./test/unit/test_coverage_summary_real.bats
file: ./tools/bats-guard.sh
file: ./tools/check_git_trash.sh
file: ./tools/churn-by-layer.sh
file: ./tools/churn_compare.sh
file: ./tools/detect_garbage.sh
file: ./tools/doctor.sh
file: ./tools/enforce_policy.sh
file: ./tools/exit_codes_enforcer.sh
file: ./tools/fix_missing_specs.sh
file: ./tools/gen_readme.sh
file: ./tools/gen_readme_updates.sh
file: ./tools/git-hooks/README.mirrored
file: ./tools/git-hooks/post-merge
file: ./tools/git-hooks/post-rewrite
file: ./tools/git-hooks/pre-commit
file: ./tools/git-hooks/pre-merge-commit
file: ./tools/git-hooks/pre-push
file: ./tools/git-hooks/pre-rebase
file: ./tools/install-hooks.sh
file: ./tools/pre-git-switch.sh
file: ./tools/providers/.gitkeep
file: ./tools/providers/localfs/.gitkeep
file: ./tools/providers/terraform/.gitkeep
file: ./tools/release/gen_notes.sh
file: ./tools/scan_duplicate_targets.sh
file: ./tools/scope-guard.sh
file: ./tools/scope2.yaml
file: ./tools/setup.sh
file: ./tools/smoke-scope-guard.sh
file: ./tools/structure/io-wrap.sh
file: ./tools/structure/negative.bats
file: ./tools/structure/refactor-wrapper.sh
file: ./tools/structure/snapshot.bats
file: ./tools/structure/structure_snapshot_gen.rf.sh
file: ./tools/structure/structure_snapshot_gen.sh
file: ./tools/structure_compare.sh
file: ./tools/utili-sourcing.sh
file: ./tools/validate_ignore.sh
file: ./util/core.rf.sh
file: ./util/core.sh
file: ./util/logger.sh
file: ./util/logger_wrapper.sh
file: ./util/source_or_fail.sh
