# Auto-generated structure.spec

dir: ./
dir: ./attn/
dir: ./bin/
dir: ./config/
dir: ./docs/
dir: ./lib/
dir: ./lib/policy/
dir: ./lib/testdata/
dir: ./system/
dir: ./system/exit-codes/
dir: ./system/make/
dir: ./test/
dir: ./test/bin-tests/
dir: ./test/e2e/
dir: ./test/e2e/features/
dir: ./test/e2e/garbage_detector/
dir: ./test/e2e/helpers/
dir: ./test/e2e/structure_generator/
dir: ./test/e2e/structure_ignore/
dir: ./test/e2e/structure_negative_tests/
dir: ./test/e2e/structure_validator/
dir: ./test/integration/
dir: ./test/lib-tests/
dir: ./test/unit/
dir: ./tools/
dir: ./tools/git-hooks/
dir: ./tools/providers/
dir: ./tools/providers/localfs/
dir: ./tools/providers/terraform/
dir: ./tools/release/
dir: ./tools/structure/
dir: ./util/
file: ./.github/pull_request_template.md
file: ./.github/workflows/check-purity.yml
file: ./.github/workflows/churn-pr.yml
file: ./.github/workflows/maat-coupling.yml
file: ./.github/workflows/scope-guard.actions.yml
file: ./.github/workflows/scope.yml
file: ./.github/workflows/shellcheck.yml
file: ./.github/workflows/structural_drift.yml
file: ./.gitignore
file: ./.structure.ignore
file: ./Makefile
file: ./README.generated.md
file: ./attn/context-status.rf.sh
file: ./attn/context-status.sh
file: ./bin/main.sh
file: ./config/enforcer_tests.txt
file: ./config/policy.rules.yml
file: ./config/runtime.cfg
file: ./config/runtime_flags.sh
file: ./docs/CHANGELOG.md
file: ./docs/Focus.txt
file: ./docs/README.generated.md
file: ./docs/README.md
file: ./lib/cmd.sh
file: ./lib/cmd2.sh
file: ./lib/command_contracts.sh
file: ./lib/contracts.sh
file: ./lib/demo.sh
file: ./lib/enums.sh
file: ./lib/env_init.sh
file: ./lib/err
file: ./lib/file.sh
file: ./lib/parse.sh
file: ./lib/pipe.sh
file: ./lib/policy/enforce_policy_p3.sh
file: ./lib/policy/enforce_record
file: ./lib/policy/enforce_record_tests.bats
file: ./lib/policy/isolated_policy_tests.bats
file: ./lib/policy/logs.txt
file: ./lib/policy/negative-e2e.bats
file: ./lib/policy/out.tsv
file: ./lib/policy/p1-p3smoke.sh
file: ./lib/policy/p1p3aggregate.bats
file: ./lib/policy/p1p3smoke.bats
file: ./lib/policy/p2_predicates.bats
file: ./lib/policy/p2p3smoke.bats
file: ./lib/policy/policy_query_p1.sh
file: ./lib/policy/policy_query_tests.bats
file: ./lib/policy/predicates-shim.sh
file: ./lib/policy/run_bats.sh
file: ./lib/policy/runner.sh
file: ./lib/policy/smk23.sh
file: ./lib/policy/smk_1-2.bats
file: ./lib/policy/smk_1-2.sh
file: ./lib/policy/smoke_test_policy.query.sh
file: ./lib/policy/testE2e.bats
file: ./lib/policy/test_shim.bats
file: ./lib/policy/transform_policy_p2.sh
file: ./lib/policy/transform_policy_rules.sh
file: ./lib/policy/transform_policy_rules_shim
file: ./lib/policy/verify_pipeline.sh
file: ./lib/predicates.sh
file: ./lib/primitive_checks.bats
file: ./lib/queries.sh
file: ./lib/run-table.sh
file: ./lib/testdata/prefer_stdin.tsv
file: ./lib/testdata/should_read_stdin.tsv
file: ./lib/trace.sh
file: ./lib/tty.sh
file: ./new.sh
file: ./scope.yaml
file: ./smoke2.sh
file: ./system/comparator.txt
file: ./system/exit-codes/exit_codes_validator.sh
file: ./system/make/garbage.mk
file: ./system/make/guard_rails.mk
file: ./system/make/guard_rails.sh
file: ./system/make/health.mk
file: ./system/make/help.mk
file: ./system/make/hooks.mk
file: ./system/make/modules.mk
file: ./system/make/preflight.mk
file: ./system/make/preflight_shared.mk
file: ./system/make/structure.mk
file: ./system/make/test.mk
file: ./system/smoke-structure-validator.sh
file: ./system/structure_spec_validator.sh
file: ./system/structure_validator.rf.sh
file: ./system/structure_validator.sh
file: ./system/validate_structure.sh
file: ./test/bin-tests/main-context-check-mock.bats
file: ./test/bin-tests/main-preflight.bats
file: ./test/bin-tests/main-structure-validator-mock.bats
file: ./test/bin-tests/smoke_test.sh
file: ./test/bin-tests/test-core__derive_root.bats
file: ./test/bin-tests/test-main.bats
file: ./test/e2e/enforce_policy.bats
file: ./test/e2e/features/drift_monitoring.feature
file: ./test/e2e/garbage_detector/test-ignore-valid.bats
file: ./test/e2e/garbage_detector/test-untracked-garbage.bats
file: ./test/e2e/helpers/.gitkeep
file: ./test/e2e/structure_generator/test-generate-spec.bats
file: ./test/e2e/structure_ignore/.structure.ignore
file: ./test/e2e/structure_ignore/test-validate-ignore.bats
file: ./test/e2e/structure_negative_tests/test-broken-symlink.bats
file: ./test/e2e/structure_negative_tests/test-invalid-structure.bats
file: ./test/e2e/structure_validator/test-raw-path.bats
file: ./test/e2e/structure_validator/test-valid-structure.bats
file: ./test/e2e/structure_validator_queries.bats
file: ./test/e2e/testing-setup.sh
file: ./test/integration/test_pre_git_switch.bats
file: ./test/lib-tests/test_logger.bats
file: ./test/lib-tests/test_logger_min.sh
file: ./test/lib-tests/test_source_safe.bats
file: ./test/toggle_module_contracts.bats
file: ./test/unit/test_coverage_summary_real.bats
file: ./tools/bats-guard.sh
file: ./tools/check_git_trash.sh
file: ./tools/churn-by-layer.sh
file: ./tools/churn_compare.sh
file: ./tools/detect_garbage.sh
file: ./tools/doctor.sh
file: ./tools/enforce_policy.sh
file: ./tools/exit_codes_enforcer.sh
file: ./tools/fix_missing_specs.sh
file: ./tools/gen_readme.sh
file: ./tools/gen_readme_updates.sh
file: ./tools/git-hooks/pre-commit
file: ./tools/git-hooks/pre-merge-check.sh
file: ./tools/git-hooks/pre-push
file: ./tools/install-hooks.sh
file: ./tools/pre-git-switch.sh
file: ./tools/providers/.gitkeep
file: ./tools/providers/localfs/.gitkeep
file: ./tools/providers/terraform/.gitkeep
file: ./tools/release/gen_notes.sh
file: ./tools/scan_duplicate_targets.sh
file: ./tools/scope-guard.sh
file: ./tools/setup.sh
file: ./tools/smoke-scope-guard.sh
file: ./tools/structure/structure_snapshot_gen.sh
file: ./tools/structure_compare.sh
file: ./tools/utili-sourcing.sh
file: ./tools/validate_ignore.sh
file: ./util/core.rf.sh
file: ./util/core.sh
file: ./util/logger.sh
file: ./util/logger_wrapper.sh
file: ./util/source_or_fail.sh
