# Auto-generated structure.spec

dir: .
dir: ./attn
dir: ./config
dir: ./modules
dir: ./modules/example_module
dir: ./modules/example_module/scripts
dir: ./modules/prototype
dir: ./modules/unit_testing
dir: ./modules/unit_testing/environment
dir: ./modules/unit_testing/experimentation
dir: ./modules/unit_testing/fsm
dir: ./modules/unit_testing/main
dir: ./system
dir: ./system-test
dir: ./system-test/garbage_detector
dir: ./system-test/structure_negative_tests
dir: ./system-test/structure_validator
dir: ./system/make
dir: ./test
dir: ./tmp
dir: ./tools
dir: ./tools/git-hooks
file: ./.DS_Store
file: ./.gitignore
file: ./.structure.ignore
file: ./Makefile
file: ./Makefile.legacy
file: ./README.md
file: ./attn/context-status.sh
file: ./config/.DS_Store
file: ./config/runtime.cfg
file: ./config/runtime_flags.sh
file: ./main.sh
file: ./modules/.DS_Store
file: ./modules/example_module/scripts/start.sh
file: ./modules/prototype/envManager.sh
file: ./modules/prototype/fsm_git_handler.sh
file: ./modules/prototype/prototypeManager.env
file: ./modules/prototype/prototype_manager2.sh
file: ./modules/prototype/prototype_requirements_02-09-25.txt
file: ./modules/prototype/truths_fsm_handler.json
file: ./modules/unit_testing/.DS_Store
file: ./modules/unit_testing/environment/context_testing.bats
file: ./modules/unit_testing/fsm/fsm_execute_git_command_tests.sh
file: ./modules/unit_testing/fsm/fsm_input_tests.bats
file: ./modules/unit_testing/fsm/fsm_input_tests.sh
file: ./modules/unit_testing/fsm/transition_testing.bats.sh
file: ./modules/unit_testing/handler.sh
file: ./modules/unit_testing/module.state
file: ./system-test/garbage_detector/test-ignore-valid.bats
file: ./system-test/garbage_detector/test-untracked-garbage.bats
file: ./system-test/structure_negative_tests/test-broken-symlink.bats
file: ./system-test/structure_negative_tests/test-invalid-structure.bats
file: ./system-test/structure_validator/test-raw-path.bats
file: ./system-test/structure_validator/test-valid-structure.bats
file: ./system/.DS_Store
file: ./system/make/garbage.mk
file: ./system/make/health.mk
file: ./system/make/hooks.mk
file: ./system/make/modules.mk
file: ./system/make/preflight.mk
file: ./system/make/structure.mk
file: ./system/make/test.mk
file: ./system/validate_structure.sh
file: ./test/toggle_module_contracts.bats
file: ./toggle.sh
file: ./tools/.DS_Store
file: ./tools/aggregate_structure.sh
file: ./tools/detect_garbage.sh
file: ./tools/doctor.sh
file: ./tools/garbage_debug_output.txt
file: ./tools/generate_all_module_specs.sh
file: ./tools/git-hooks/pre-push
file: ./tools/install-hooks.sh
file: ./tools/setup.sh
file: ./tools/test_write.txt
file: ./tools/untracked_debug.txt
file: ./tools/validate_ignore.sh
