name: purity
on: [push, pull_request]
jobs:
  purity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x ci/check_*.sh
      - run: ci/check_predicates.sh
      - run: ci/check_queries.sh
      - run: ci/check_contracts.sh
      - run: ci/check_frames.sh
