name: codescene-pr
on: pull_request
jobs:
  codescene:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    permissions: { contents: read }
    env:
      CODESCENE_DELTA_ANALYSIS_URL: ${{ secrets.CODESCENE_DELTA_ANALYSIS_URL }}
      CODESCENE_USER:               ${{ secrets.CODESCENE_USER }}
      CODESCENE_PASSWORD:           ${{ secrets.CODESCENE_PASSWORD }}
      GITHUB_API_TOKEN:             ${{ secrets.CODESCENE_GH_PAT }}  # repo scope (or public_repo)
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }

      - name: Download CodeScene CI/CD CLI
        run: |
          curl -fsSL -o codescene-ci-cd.jar \
            https://github.com/empear-analytics/codescene-ci-cd/releases/download/v1.3.3/codescene-ci-cd-1.3.3-standalone.jar

      - name: Run delta analysis and comment
        run: |
          java -jar codescene-ci-cd.jar \
            --codescene-delta-analysis-url "${CODESCENE_DELTA_ANALYSIS_URL}" \
            --codescene-user "${CODESCENE_USER}" \
            --codescene-password "${CODESCENE_PASSWORD}" \
            --analyze-branch-diff \
            --create-github-comment \
            --github-api-url "https://api.github.com" \
            --github-api-token "${GITHUB_API_TOKEN}" \
            --github-owner "${{ github.repository_owner }}" \
            --github-repo  "${{ github.event.repository.name }}" \
            --github-pull-request-id "${{ github.event.pull_request.number }}" \
            --coupling-threshold-percent 75 \
            --fail-on-high-risk \
            --result-path result.json \
            --log-result
