# .github/workflows/codescene-pr.yml
name: codescene-pr
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codescene:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CODESCENE_DELTA_ANALYSIS_URL: ${{ secrets.CODESCENE_DELTA_ANALYSIS_URL }}
      CODESCENE_USER:               ${{ secrets.CODESCENE_USER }}
      CODESCENE_PASSWORD:           ${{ secrets.CODESCENE_PASSWORD }}
      GITHUB_API_TOKEN:             ${{ secrets.CODESCENE_GH_PAT }}  # PAT with repo/public_repo
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Download CodeScene CI/CD CLI
        env:
          TAG: v1.3.3
          REPO: empear-analytics/codescene-ci-cd
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          api="https://api.github.com/repos/$REPO/releases/tags/$TAG"
          url="$(curl -fsSL -H "Authorization: Bearer $GH_TOKEN" "$api" \
            | jq -r '.assets[] | select(.name | test("standalone\\.jar$")) | .browser_download_url')"
          if [[ -z "$url" || "$url" == "null" ]]; then
            echo "No standalone jar found on $TAG" >&2
            curl -fsSL -H "Authorization: Bearer $GH_TOKEN" "$api" | jq -r '.assets[].name' >&2
            exit 1
          fi
          curl -fsSL -o codescene-ci-cd.jar "$url"
          java -jar codescene-ci-cd.jar --help >/dev/null

      - name: Run CodeScene delta analysis and comment
        run: |
          java -jar codescene-ci-cd.jar \
            --codescene-delta-analysis-url "${CODESCENE_DELTA_ANALYSIS_URL}" \
            --codescene-user "${CODESCENE_USER}" \
            --codescene-password "${CODESCENE_PASSWORD}" \
            --analyze-branch-diff \
            --create-github-comment \
            --github-api-url "https://api.github.com" \
            --github-api-token "${GITHUB_API_TOKEN}" \
            --github-owner "${{ github.repository_owner }}" \
            --github-repo  "${{ github.event.repository.name }}" \
            --github-pull-request-id "${{ github.event.pull_request.number }}" \
            --coupling-threshold-percent 75 \
            --fail-on-high-risk \
            --result-path result.json \
            --log-result

      - name: Upload result.json
        if: ${{ always() && hashFiles('result.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: codescene-result
          path: result.json
