# .github/workflows/codescene-pr.yml
name: codescene-pr
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codescene:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CODESCENE_DELTA_ANALYSIS_URL: ${{ secrets.CODESCENE_DELTA_ANALYSIS_URL }}
      CODESCENE_USER:               ${{ secrets.CODESCENE_USER }}
      CODESCENE_PASSWORD:           ${{ secrets.CODESCENE_PASSWORD }}
      GITHUB_API_TOKEN:             ${{ secrets.CODESCENE_GH_PAT }}  # PAT with repo/public_repo
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install GitHub CLI (fallback)
        uses: cli/cli@v2
        with:
          version: 2.54.0

      - name: Download CodeScene CI/CD CLI
        env:
          TAG: v1.3.3
          REPO: empear-analytics/codescene-ci-cd
        run: |
          set -euo pipefail
          mkdir -p .cache
          JAR=".cache/codescene-ci-cd.jar"
          if [[ ! -s "$JAR" ]]; then
            for NAME in \
              "codescene-ci-cd-${TAG#v}-standalone.jar" \
              "codescene-ci-cd-standalone.jar"; do
              URL="https://github.com/$REPO/releases/download/$TAG/$NAME"
              echo "Trying $URL"
              if curl -fL --retry 5 --retry-delay 2 --retry-all-errors -o "$JAR" "$URL"; then
                break
              fi
            done
            if [[ ! -s "$JAR" ]]; then
              echo "Falling back to gh release download"
              gh release download "$TAG" -R "$REPO" -p '*standalone.jar' -O "$JAR"
            fi
          fi
          java -jar "$JAR" --help >/dev/null

      - name: Run CodeScene delta analysis and comment
        run: |
          java -jar .cache/codescene-ci-cd.jar \
            --codescene-delta-analysis-url "${CODESCENE_DELTA_ANALYSIS_URL}" \
            --codescene-user "${CODESCENE_USER}" \
            --codescene-password "${CODESCENE_PASSWORD}" \
            --analyze-branch-diff \
            --create-github-comment \
            --github-api-url "https://api.github.com" \
            --github-api-token "${GITHUB_API_TOKEN}" \
            --github-owner "${{ github.repository_owner }}" \
            --github-repo  "${{ github.event.repository.name }}" \
            --github-pull-request-id "${{ github.event.pull_request.number }}" \
            --coupling-threshold-percent 75 \
            --fail-on-high-risk \
            --result-path result.json \
            --log-result

      - name: Upload result.json
        if: ${{ always() && hashFiles('result.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: codescene-result
          path: result.json
