name: Deploy
on:
  workflow_dispatch:
    inputs:
      env: { default: production }
      sha: { required: false }

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4g
        with:
          ref: ${{ inputs.sha || github.sha }}
 
      - name: Ensure tools
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run deploy executor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x bin/deploy_exec.sh
          bin/deploy_exec.sh "${{ inputs.env || 'production' }}"

      - name: Validate events.ndjson
        run: bash ci/probe.sh --kind=events events.ndjson

      - name: Upload events.ndjson
        uses: actions/upload-artifact@v4
        with:
          name: events-ndjson
          path: events.ndjson
          retention-days: 21
