name: Deploy
on:
  workflow_dispatch:
    inputs:
      env: { default: production }
      sha: { description: "Commit SHA", required: false }


permissions:
  contents: read
  actions: write   # needed for gh workflow run

 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Ensure tools
        run: |
          gh --version || sudo apt-get update && sudo apt-get install -y gh
          jq --version || sudo apt-get install -y jq

      - name: Run deploy with polling + assert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x bin/deploy.sh
          bin/deploy.sh "${{ inputs.env || 'production' }}"

      - name: Upload events
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: events-ndjson
          path: events.ndjson
          retention-days: 21



