name: pr-merged
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  emit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y jq
      - name: emit pr_merged
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash ci/dora/event-append.sh pr-merged
      - uses: actions/upload-artifact@v4
        with:
          name: pr-only
          path: events.ndjson
