# .github/workflows/roi-aggregator-shadow.yml
name: ROI Aggregator

on:
  schedule: [{ cron: "37 02 * * *" }]
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/roi-aggregator-shadow.yml"
      - "ci/roi/**"
      - "scripts/roi/**"

permissions:
  contents: read
  actions: read

concurrency:
  group: roi-aggregator-shadow
  cancel-in-progress: true

jobs:
  roi:
    runs-on: ubuntu-latest
    env:
      WINDOW_DAYS: "14"
      HEAD_BRANCH: "main"                                     # match your scope
      RUN_NAME_REGEX: "(?i)(accept|purity|structure|shellcheck)"
      DURATION_METRIC: "p50"                                  # mean|p50
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y jq gh unzip

      - name: Fetch required artifacts
 

        env: 
          REPO: ${{ github.repository }}
 
        run: bash ./ci/roi/fetch_artifacts.sh

      - name: Freeze baseline (optional)
        run: |
          if [[ -f ci/roi/baseline_frozen.json ]]; then
            cp ci/roi/baseline_frozen.json baseline.json
            echo "Using baseline_frozen.json" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Build inputs from artifacts
        id: inputs
        run: bash ci/roi/build_inputs.sh

 
      # ----- new implementation -----
       - name: ROI (new)
         env:
          WINDOW_DAYS: ${{ env.WINDOW_DAYS }}
          RUNS:  ${{ steps.inputs.outputs.runs }}
          TA:    ${{ steps.inputs.outputs.avg_sec }}
          PRS:   ${{ steps.inputs.outputs.total }}
          PA:    ${{ steps.inputs.outputs.pa }}
          TB:    ${{ steps.inputs.outputs.tb }}
          PB:    ${{ steps.inputs.outputs.pb }}
          R:     ${{ steps.inputs.outputs.r }}
          H:     ${{ steps.inputs.outputs.hours }}

        run: |
          python3 ci/roi/compute_roit.py | tee -a "$GITHUB_STEP_SUMMARY"
          mv roit.json roit_new.json
 
      - name: Upload ROI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: roi-outputs
          path: |
            roit.json
            roit_old.json
            roit_new.json
          retention-days: 30
