# .github/workflows/roi-aggregator-shadow.yml
name: ROI Aggregator (Shadow)

on:
  schedule: [{ cron: "37 02 * * *" }]
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/roi-aggregator-shadow.yml"
      - "ci/roi/**"
      - "scripts/roi/**"

permissions:
  contents: read
  actions: read

concurrency:
  group: roi-aggregator-shadow
  cancel-in-progress: true

jobs:
  roi:
    runs-on: ubuntu-latest
    env:
      WINDOW_DAYS: "14"
      HEAD_BRANCH: "main"                                     # match your scope
      RUN_NAME_REGEX: "(?i)(accept|purity|structure|shellcheck)"
      DURATION_METRIC: "p50"                                  # mean|p50
      USE_NEW_ROI: "false"                                    # flip to roll forward
      SHADOW_TOL: "0.05"                                      # ≤5% delta allowed
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y jq gh unzip

      - name: Fetch required artifacts
 

        env: 
          REPO: ${{ github.repository }}
 
        run: bash ./ci/roi/fetch_artifacts.sh

      - name: Freeze baseline (optional)
        run: |
          if [[ -f ci/roi/baseline_frozen.json ]]; then
            cp ci/roi/baseline_frozen.json baseline.json
            echo "Using baseline_frozen.json" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Build inputs from artifacts
        id: inputs
        run: bash ./ci/roi/build_inputs.sh

      # ----- old implementation -----
      - name: ROI (old)
        run: |
          python3 ./ci/roi/compute_roit_old.py | tee -a "$GITHUB_STEP_SUMMARY"
          mv roit.json roit_old.json

      # ----- new implementation -----
      - name: ROI (new)
        run: |
          python3 ./ci/roi/compute_roit.py | tee -a "$GITHUB_STEP_SUMMARY"
          mv roit.json roit_new.json

      - name: Compare old vs new
        env:
          SHADOW_TOL: ${{ env.SHADOW_TOL }}
          MODE: warn                                           # warn|fail
        run: |
          python3 ./ci/roi/shadow_diff.py roit_old.json roit_new.json | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Select version to publish
        id: choose
        run: |
          if [[ "${USE_NEW_ROI}" == "true" ]]; then
            cp roit_new.json roit.json
            echo "picked=new" >> "$GITHUB_OUTPUT"
          else
            cp roit_old.json roit.json
            echo "picked=old" >> "$GITHUB_OUTPUT"
          fi
          echo "- Selected ROI: ${{ steps.choose.outputs.picked }}" >> "$GITHUB_STEP_SUMMARY"

      - name: Upload ROI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: roi-outputs
          path: |
            roit.json
            roit_old.json
            roit_new.json
          retention-days: 30
