# .github/workflows/roi-baseline.yml  (or keep baseline.json in repo)
name: ROI Baseline Publisher
on:
  schedule: [{cron: "17 02 * * *"}]
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [dev, main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir out
          cat > out/baseline.json <<'JSON'
          { "avg_duration_before_sec": 20,
            "p_before": 0.70,
            "rework_hours_per_failed_pr": 2.0 }
          JSON
      - uses: actions/upload-artifact@v4
        with: { name: roi-baseline, path: out/baseline.json, retention-days: 180 }
