# .github/workflows/scope-guard.yml
name: scope-guard
on:
  pull_request:
    branches: [main]

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout PR HEAD (full history)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }} --depth=1

      - name: Install yq
        uses: mikefarah/yq@v4.44.3

      - name: Verify yq
        run: |
          yq --version
          command -v yq

      - name: Compute base and run scope guard (diagnostic)
        run: |
          set -euo pipefail
          set -x
          echo "HEAD=$(git rev-parse --short HEAD)"
          BASE_COMMIT="$(git merge-base HEAD "origin/${{ github.base_ref }}")"
          echo "Using base $BASE_COMMIT"

          test -f tools/scope_guard.sh
          chmod +x tools/scope_guard.sh || true
          ls -l tools

          set +e
          BASE="$BASE_COMMIT" bash tools/scope_guard.sh
          rc=$?
          set -e
          echo "scope_guard rc=$rc"
          exit $rc
