# .github/workflows/scope.yml
name: scope-guard
on: [pull_request]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mikefarah/yq@v4.44.3
      - run: bash tools/scope_guard.sh
