name: Structure Validation (diagnostic)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run structure validator (diagnostic)
        run: |
          set -euo pipefail
          SCRIPT="system/structure_validator.rf.sh"
          chmod +x "$SCRIPT"
          "$SCRIPT" validate structure.spec

      - name: Run structure validator (diagnostic)
        env:
          MINIMAL_MODE: "1"                       # run without local utility deps
          SPEC_SEARCH_PATHS: ".:config:system-test"
          LOG_OUTPUT_FILE: "structure_validator.jsonl"
          LOG_FILE: "structure_validator.log"
        run: |
          set -euo pipefail
          set -x
          echo "PWD=$(pwd)"
          git rev-parse --short HEAD || true
          ls -la
          ls -la system || true
          ls -la config || true

          # adjust path if your script lives elsewhere
          SCRIPT="system/structure_validator.rf.sh"
          test -f "$SCRIPT"
          chmod +x "$SCRIPT"

          set +e
          "$SCRIPT" --spec structure.spec
          rc=$?
          set -e
          echo "validator rc=$rc"

          echo "--- JSON log ---"
          if [ -f "$LOG_OUTPUT_FILE" ]; then sed -n '1,200p' "$LOG_OUTPUT_FILE"; else echo "(missing)"; fi
          echo "--- TEXT log ---"
          if [ -f "$LOG_FILE" ]; then sed -n '1,200p' "$LOG_FILE"; else echo "(missing)"; fi

          exit $rc
          

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: structure-validator-logs
          path: |
            structure_validator.jsonl
            structure_validator.log
