name: Structure Validation

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  validate-structure:
    runs-on: ubuntu-latest

    env:
      # Prevent sourcing local-only utilities in CI
      MINIMAL_MODE: "1"
      # Make spec lookup deterministic
      SPEC_SEARCH_PATHS: .:config:system-test
      # CI log files
      LOG_OUTPUT_FILE: structure_validator.jsonl
      LOG_FILE: structure_validator.log

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure script is executable
        run: chmod +x system/structure_validator.rf.sh

      - name: Run structure validator
        run: |
          set -euo pipefail
          system/structure_validator.rf.sh --spec structure.spec

      - name: Upload logs as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: structure-validator-logs
          path: |
            structure_validator.jsonl
            structure_validator.log
